
let cartBody = document.querySelector('.cart__body');
const item = document.createElement('div');
item.classList.add('cart__item');
const itemPhoto = document.createElement('div');
itemPhoto.classList.add('cart__item_photo');
item.append(itemPhoto);
const itemBody = document.createElement('div');
itemBody.classList.add('cart__item_body');
item.appendChild(itemBody);
const img = document.createElement('img');
img.src = localStorage.getItem('img');
itemPhoto.appendChild(img);
const itemTitle = document.createElement('div');
itemBody.append(itemTitle);
itemTitle.classList.add('cart__item_title');
itemTitle.innerHTML = localStorage.getItem('name');
const price = document.createElement('div');
itemBody.appendChild(price);
price.classList.add('cart__item_price');
price.innerHTML = '$' + localStorage.getItem('price');
const itemButton = document.createElement('button');
itemButton.classList.add('item__delete');
item.appendChild(itemButton);
const imgButton = document.createElement('img');
itemButton.append(imgButton);
imgButton.src = '../icons/page_cart/close.svg';
cartBody.prepend(item);

console.log(cartBody);
